storage: /verdaccio/storage

listen: 0.0.0.0:4873

web:
  enable: true
  title: proxy-gateway local registry

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@echospecter/proxy-fetch':
    access: $all
    proxy: npmjs

  '@echospecter/*':
    access: $all
    publish: $anonymous
    unpublish: $anonymous

  '**':
    access: $all
    publish: $anonymous
    unpublish: $anonymous
    proxy: npmjs

middlewares:
  audit:
    enabled: false

log:
  type: stdout
  format: pretty
  level: http
