export const WIRE_PROTOCOL_VERSION = 'proxy-fetch.v1';

export enum RESPONSE_CODE {
  INVALID_PROXY_FETCH_REQUEST = 'INVALID_PROXY_FETCH_REQUEST',
  NO_PROVIDER_AVAILABLE = 'NO_PROVIDER_AVAILABLE',
  TRANSPORT_NOT_CONFIGURED = 'TRANSPORT_NOT_CONFIGURED',
}
